### ISSUE TITLE
[Tracking Issue] Julia Cooperative Multithreading Benchmarks

### ISSUE THREAD

**Issue by NHDaly** [RelationalAI-oss/MultithreadingBenchmarks.jl#1]
This is a tracking issue tracking our experiments benchmarking Julia's new cooperative multithreading (experimentally introduced in Julia `v1.3` via `@spawn`).

# List of Experiments:
- [x] Independent tasks parallelism scaling experiment: #2
- [x] All threads allocating parallelism scaling experiment: #3
- [ ] One thread allocating parallelism scaling experiment: #4
